### PR TITLE
Fix numpy2 and scipy compatibility

### PR DESCRIPTION
**Pull request by felipeacsi**
Hello Alexander,

currently `pyva` is not working with Numpy 2 but fortunately there is only one line affected as it is stated in this error:

```python

AttributeError('`np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.')
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/models.py", line 11, in <module>
    import pyva.properties.materialClasses as matC
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/properties/materialClasses.py", line 1368, in <module>
    class PoroElasticMat(EquivalentFluid):
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/properties/materialClasses.py", line 1395, in PoroElasticMat
    Cp=1005.1, heat_conductivity = 0.0257673 , Ks = np.Inf):
                                                    ^^^^^^
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
```

As far as I could trace, `np.inf` [is available at least from Numpy 1.15](https://numpy.org/doc/1.15/reference/constants.html?highlight=inf#numpy.inf) so the change I'm proposing it's ok since the dependencies in the `pyproject.toml` is `numpy>=1.20.2`.

I've also checked with `ruffus` as it is recommended [in the Numpy docs](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#ruff-plugin) and only found this problem, so there is only one compatibility error.

Kind regards,

Felipe

PS: Output of `ruffus` if you are curious:

```python

pyva/properties/materialClasses.py:1321:71: NPY201 [*] `np.Inf` will be removed in NumPy 2.0. Use `numpy.inf` instead.
     |
1319 |                       flow_res,porosity,tortuosity,length_visc,length_therm,limp = False,\
1320 |                       c0=343.,rho0=1.23,dynamic_viscosity=1.84e-5,kappa = 1.4, \
1321 |                       Cp=1005.1, heat_conductivity = 0.0257673 , Ks = np.Inf):
     |                                                                       ^^^^^^ NPY201
1322 |         """
1323 |         Construcutor of equivalent fluid class.
     |
     = help: Replace with `numpy.inf````

### CODE REVIEW

**Comment by felipeacsi** [comment]
So, there is also a compatibility issue with SciPy. Here is the error:

```python

AttributeError("module 'scipy.integrate' has no attribute 'trapz'")
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/models.py", line 2016, in create_SEA_matrix
    jm = jun.junction_matrix(omega)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/coupling/junctions.py", line 1966, in junction_matrix
    JM[ir,ic,:] = -mod_dens[ic]*self.CLF_structure_fluid(omega,ix_cavity = ir, pos_dir = True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/coupling/junctions.py", line 1828, in CLF_structure_fluid
    sigma = self.plate.radiation_efficiency(omega,cavity.fluid,Nstep = 90)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/systems/structure2Dsystems.py", line 578, in radiation_efficiency
    sigma[ifreq] = 2/np.pi*integrate.trapz(sigs,phi)
                           ^^^^^^^^^^^^^^^
```

The origin of this is that `scipy.integrate.trapz` was renamed to `scipy.integrate.trapezoid` back in version `scipy 1.6.0` ([docs](https://docs.scipy.org/doc/scipy/release/1.6.0-notes.html#scipy-integrate-improvements])). Since `pyproject.toml` indicates `scipy >= 1.6.2`, the proposed change in https://github.com/minipief/pyva/pull/9/commits/b150042f07c672e2baac54d52b618e9fff8bd356 doesn't need an update of dependencies.

At this point I don't know if other issues may arise.

I think it is good to merge.

Best regards,

Felipe

**Comment by minipief** [comment]
Hi Felipe,Thank for the comment. You always got me in my holidays :) and I am always learning. I did not notice yet that there is a numpy 2.It all sounds reasonable and I will check when I am back next week.Best,Alexander Am 17.09.2024 01:52 schrieb Felipe Raimann ***@***.***>:Hello Alexander,
currently pyva is not working with Numpy 2 but fortunately there is only one line affected as it is stated in this error:
AttributeError('`np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.')
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/models.py", line 11, in <module>
    import pyva.properties.materialClasses as matC
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/properties/materialClasses.py", line 1368, in <module>
    class PoroElasticMat(EquivalentFluid):
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/pyva/properties/materialClasses.py", line 1395, in PoroElasticMat
    Cp=1005.1, heat_conductivity = 0.0257673 , Ks = np.Inf):
                                                    ^^^^^^
  File "/home/user/.uvenv/dev/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
As far as I could trace, np.inf is available at least from Numpy 1.15 so the change I'm proposing it's ok since the dependencies in the pyproject.toml is numpy>=1.20.2.
I've also checked with ruffus as it is recommended in the Numpy docs and only found this problem, so there is only one compatibility error.
Kind regards,
Felipe
PS: Output of ruffus if you are curious:
pyva/properties/materialClasses.py:1321:71: NPY201 [*] `np.Inf` will be removed in NumPy 2.0. Use `numpy.inf` instead.
     |
1319 |                       flow_res,porosity,tortuosity,length_visc,length_therm,limp = False,\
1320 |                       c0=343.,rho0=1.23,dynamic_viscosity=1.84e-5,kappa = 1.4, \
1321 |                       Cp=1005.1, heat_conductivity = 0.0257673 , Ks = np.Inf):
     |                                                                       ^^^^^^ NPY201
1322 |         """
1323 |         Construcutor of equivalent fluid class.
     |
     = help: Replace with `numpy.inf````



You can view, comment on, or merge this pull request online at:
  https://github.com/minipief/pyva/pull/9

Commit Summary
455339c  Fix numpy2 compatibility

File Changes  (1 file)

    M
    pyva/properties/materialClasses.py
    (4)
  

Patch Links:
https://github.com/minipief/pyva/pull/9.patchhttps://github.com/minipief/pyva/pull/9.diff

**Comment by felipeacsi** [comment]
Sorry about that!

Happy Holidays!

**Comment by minipief** [comment]
Your proposal is merged into the project. Thanks a lot for your input.

Best
Alexander

**Comment by minipief** [comment]
Ah and by the way. The Ks argument was not needed. This is an assumption (Ks>> 1)  that is valid for nearly all practical materials.
So, I will delete this argument in the next commit. 

Thanks in any case, I really appreciate your support to my code.

Best regards again,
Alexander

**Pull request merged**
